project:
  type: website

website:
  title: "JRM"
  search: false
  google-analytics: "G-HGDK549CZ5"
  navbar:
    left:
      - text: "About"
        href: about.html
      - text: "Publications"
        href: publications.html
      - text: "CV"
        href: cv.html

format:
  html:
    page-layout: full
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: false
    include-in-header:
      - text: |
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css">

editor: visual