---
title: ""
---

# Publications

## Water Quality & Coastal Systems

-   **Montiel-Mora, J. R.**, Gómez-Ramirez, E., Irías-Mata, A., Chacón-Jiménez, L., Barrantes-Jiménez, K., & Fuentes-Schweizer, P. (2025). *Application of three water quality indices in a tropical river of Costa Rica: the case of the Durazno River.* UNED Research Journal. <https://doi.org/10.22458/urj.v17i1.5921>

-   **Montiel-Mora, J. R.**, Gómez-Ramírez, E., & Sibaja-Cordero, J. (2025). *An analysis of human impact on sandy coasts of the Costa Rican Pacific.* Marine Pollution Bulletin. <https://doi.org/10.1016/j.marpolbul.2025.117656>

-   **Montiel-Mora, J. R.**, Gómez-Ramírez, E. (2023). *Physicochemical and Microbiological Quality of Coastal Water in Nicoya, Costa Rica: Comparison of Three Beaches with Different Tourist Impact and Management.* UNED Research Journal. <https://doi.org/10.22458/urj.v15i2.4763>

------------------------------------------------------------------------

## Ecotoxicology & Emerging Contaminants

-   **Montiel-Mora, J. R.**, Lizano-Fallas, V., Méndez-Rivera, M., Marín-González, A., Cambronero-Heinrichs, J. C., & Rodríguez-Rodríguez, C. E. (2025). *Individual and mixture effect of selected high-hazard pharmaceuticals on aquatic primary producers.* Ecotoxicology. <https://doi.org/10.1007/s10646-025-02885-w>

-   **Montiel-Mora, J. R.**, Méndez-Rivera, M., Ramírez-Morales, D., Cambronero-Heinrichs, J. C., & Rodríguez-Rodríguez, C. E. (2024). *Toxicity of selected pharmaceuticals and their mixtures to the aquatic indicators Daphnia magna and Aliivibrio fischeri.* Ecotoxicology. <https://doi.org/10.1007/s10646-024-02798-0>

-   Ramírez-Morales, D., Masis-Mora, M., **Montiel-Mora, J. R.**, Méndez-Rivera, M., Gutiérrez-Quirós, J. A., Brenes-Alfaro, L., & Rodríguez-Rodríguez, C. E. (2024). *Pharmaceuticals, hazard and ecotoxicity in surface and wastewater in a tropical dairy production area in Latin America.* Chemosphere. <https://doi.org/10.1016/j.chemosphere.2023.140443>

-   Méndez-Rivera, M., **Montiel-Mora, J. R.**, Ramírez-Morales, D., Masis-Mora, M., & Rodríguez-Rodríguez, C. E. (2023). *On-farm Occurrence of Pharmaceuticals and Their Environmental Hazard: Case Study of a Tropical Dairy Farm.* Bulletin of Environmental Contamination and Toxicology. <https://doi.org/10.1007/s00128-023-03809-2>

-   Rodríguez-Rodríguez, C. E., Ramírez-Morales, D., Masis-Mora, M., **Montiel-Mora, J. R.**, Soto-Garita, C., Araya-Valverde, E., Cambronero-Heinrichs, J. C., Sánchez-Melsió, A., Briceño-Guevara, S., & Balcázar, J. L. (2023). *Occurrence and risk assessment of pharmaceuticals in hospital wastewater in Costa Rica.* Chemosphere, 339. <https://doi.org/10.1016/j.chemosphere.2023.139746>

-   Ramírez-Morales, D., Masis-Mora, M., **Montiel-Mora, J. R.**, Cambronero-Heinrichs, J. C., Pérez-Rojas, G., Tormo-Budowski, R., Méndez-Rivera, M., Briceño-Guevara, S., Gutiérrez-Quirós, J. A., Arias-Mora, V., Brenes-Alfaro, L., Beita-Sandí, W., & Rodríguez-Rodríguez, C. E. (2021). *Multi-residue analysis of pharmaceuticals in water samples by liquid chromatography-mass spectrometry: Quality assessment and application to the risk assessment of urban-influenced surface waters in a metropolitan area of Central America.* Process Safety and Environmental Protection. <https://doi.org/10.1016/j.psep.2021.07.025>

-   Ramírez-Morales, D., Masís-Mora, M., Beita-Sandí, W., **Montiel-Mora, J. R.**, Fernández-Fernández, E., Méndez-Rivera, M., Arias-Mora, V., Leiva-Salas, A., Brenes-Alfaro, L., & Rodríguez-Rodríguez, C. E. (2021). *Pharmaceuticals in farms and surrounding surface water bodies: Hazard and ecotoxicity in a swine production area in Costa Rica.* Chemosphere. <https://doi.org/10.1016/j.chemosphere.2021.129574>

-   Ramírez-Morales, D., Masis-Mora, M., **Montiel-Mora, J. R.**, Cambronero-Heinrichs, J. C., Briceño-Guevara, S., Rojas-Sánchez, C. E., Méndez-Rivera, M., Arias-Mora, V., Tormo-Budowski, R., Brenes-Alfaro, L., & Rodríguez-Rodríguez, C. E. (2020). *Occurrence of pharmaceuticals, hazard assessment and ecotoxicological evaluation of wastewater treatment plants in Costa Rica.* Science of the Total Environment. <https://doi.org/10.1016/j.scitotenv.2020.141200>

------------------------------------------------------------------------

## Risk Assessment & Agroecosystems

-   **Montiel-Mora, J. R.**, Pérez-Rojas, G., Brenes-Alfaro, L., & Rodríguez-Rodríguez, C. E. (2025). *Multiple exposure pathways to pesticide residues in tropical agroecosystems: A human health risk assessment in Costa Rica.* Environmental Monitoring & Assessment. <https://doi.org/10.1007/s10661-025-14869-8>

-   Méndez-Rivera, M., Ramírez-Morales, D., **Montiel-Mora, J. R.**, & Rodríguez-Rodríguez, C. E. (2023). *Ecotoxicity of pesticide formulations and their mixtures: the case of potato crops in Costa Rica.* Ecotoxicology. <https://doi.org/10.1007/s10646-023-02648-5>

------------------------------------------------------------------------

## Antimicrobial Resistance & Microbial Risk

-   **Montiel-Mora, J. R.**, Segura-Arroyo, P., Barrantes-Jiménez, K., Mendoza-Guido, B., & Chacón-Jiménez, L. (2026). *Antimicrobial Resistance in Coastal Waters of Latin America: Current Knowledge and Challenges.* Discovery Health. <https://doi.org/10.1186/s12982-026-01617-7>

-   **Montiel-Mora, J. R.**, Rivera-Montero, L., Badilla-Aguilar, A., Barrantes-Jiménez, K., Rivera-Navarro, P., & Chacón-Jiménez, L. (2026). *Antimicrobial resistance and phylogenetic diversity of Escherichia coli isolates from coastal recreational waters in Costa Rica.* Environmental Monitoring & Assessment. <https://doi.org/10.1007/s10661-026-15002-z>

-   Morales-Mora, E., Rivera-Montero, L., Ramos-Montalvo, N., **Montiel-Mora, J. R.**, Mendoza-Guido, B., Alfaro-Arrieta, E., Rivera-Navarro, P., Barrantes-Jiménez, K., & Chacón-Jiménez, L. (2026). *Applying weighted quantile sum regression to wastewater surveillance: enteric viral mixtures and diarrheal disease trends in Costa Rica.* Water & Health. <https://doi.org/10.2166/wh.2026.197>

-   Mendoza-Guido, B., **Montiel-Mora, J. R.**, Ureña-Salazar, C., Barrantes-Jiménez, K., & Chacón-Jiménez, L. (2025). *Molecular epidemiology of aquatic environments: challenges from sampling to implementation of surveillance programs.* Antibiotics. <https://doi.org/10.3389/fpubh.2025.1652535>

-   Barrantes-Jiménez, K., Mendoza-Guido, B., Morales-Mora, E., Rivera-Montero, L., **Montiel-Mora, J. R.**, Chacón-Jiménez, L., Rojas-Jiménez, K., & Arias-Andrés, M. (2025). *Influence of Seasonality and Pollution on the Presence of Antibiotic Resistance Genes and Potentially Pathogenic Bacteria in a Tropical Urban River.* Antibiotics. <https://doi.org/10.3390/antibiotics14080798>

-   Morales-Mora, E., Rivera-Montero, L., **Montiel-Mora, J. R.**, Barrantes-Jiménez, K., & Chacón-Jiménez, L. (2024). *Assessing Microbial Risk of Escherichia coli: A spatial and temporal study of virulence and resistance genes in surface water in resource-limited regions.* Science of The Total Environment. <https://doi.org/10.1016/j.scitotenv.2024.178044>
